services:
  dojo:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: gdb-dojo
    ports:
      - "7681:7681"
    volumes:
      - .:/dojo
    working_dir: /dojo
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    ulimits:
      core:
        soft: -1
        hard: -1
